version: '3.7'

services:
  mysql:
    image: mysql:8.0.16
    volumes:
      - database_volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - 3306:3306

  app:
    build: .
    ports:
      - 8888:8000
    depends_on:
      - mysql
    volumes:
      - .:/app
    working_dir: /app

volumes:
  database_volume: